version: '3.8'
services:
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=postgres
      - POSTGRES_DB=market_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '54320:5432'
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5
  redis:
    image: redis/redis-stack:latest
    ports:
      - '63790:6379'
      - '8001:8001'
    volumes:
      - cache_db:/data
volumes:
  postgres-data:
  cache_db:

